### ISSUE TITLE
SM-A300FU: Cellular Data and Audio

### ISSUE THREAD

**Issue by zyzz777** [vlw/android_device_samsung_a3lte#1]
Hi, I tried the 17.1 LineageOS build made by you, the one released in 20/07, but I've issued some problems, one is cellular data, which I think isn't loaded at all, maybe because of this commit 290ed433cdcad2ee0f5705c4f2beea07ee228adc

The other problem is the Audio, I don't know if its correlated with the problem before, but even with headphones I can't ear multimedia, literally never, not even a single sound from the phone.

The other things I tried were all working, very nice build, good job with what you're doing. The rom is very stable and nice. Thank you 😄 

P.S.: I switched this version to an older one (15.1), and audio and cellular data started working again, that's why i think it isn't my phone's fault

**Comment by zyzz777** [comment]
Ok, the problem was that I was using a different TWRP, use the one in the download package. Now everything works perfectly, thank you.

**Comment by casperrutten** [comment]
@zyzz777 Where can I find the package download?
