### ISSUE TITLE
Can anyone provide the recovery for a300fu?

### ISSUE THREAD

**Issue by Ud4ba** [vlw/android_device_samsung_a3lte#14]
I just need the right on recovery . thanks in advance!

**Comment by Beatz106** [comment]
The recovery is generic for the entire series. the "recommended" version is in https://androidfilehost.com/?fid=8889791610682896177

There are newer versions of the recovery on the official TWRP page, they have not been tested, waiting for results of other users who have done the tests.

**Comment by Ud4ba** [comment]
Thanks.

**Comment by Ud4ba** [comment]
> 
> 
> The recovery is generic for the entire series. the "recommended" version is in https://androidfilehost.com/?fid=8889791610682896177
> 
> There are newer versions of the recovery on the official TWRP page, they have not been tested, waiting for results of other users who have done the tests.

i think i already have this installed . i felt weird when i connect the phone , while in recovery with usb and wrote sm-a300 and not sm-a300fu , so this is right! thanks!
do you have any news on this ROM ?

**Comment by Beatz106** [comment]
the newest (in theory) would be changes in the repository, there is another developer working on the MSM8916, but, he doesn't have any variant of the Galaxy A3, making any effort useless.

**Comment by Ud4ba** [comment]
> 
> 
> the newest (in theory) would be changes in the repository, there is another developer working on the MSM8916, but, he doesn't have any variant of the Galaxy A3, making any effort useless.

do you know where i can find the other one?

**Comment by Beatz106** [comment]
https://github.com/vlw/android_device_samsung_a3lte/issues/10

**Comment by Ud4ba** [comment]
This is the telegram group of the ROM .
https://web.telegram.org/#/im?p=@a300lineage_en

**Comment by vlw** [comment]
https://t.me/a300lineage_en
