### ISSUE TITLE
a33g: Remove content related to the NFC function from source.

### ISSUE THREAD

**Issue by Beatz106** [vlw/android_device_samsung_a3lte#6]
**The problem is an old acquaintance, it has been around since the Nougat builds.**

The specifications clearly state that this version (A300H as an example) doesn't have NFC, its removal was promised in [89dd3fc](https://github.com/vlw/android_device_samsung_a3lte/commit/89dd3fc95208fd11296a427ffd42b88d019cef42) 

Keeping these services in the system running in the background causes enormous battery drain

![Screenshot_20201118-233758_Termux](https://user-images.githubusercontent.com/74375581/99630763-0bb96c80-2a00-11eb-9f0f-a392b5572b87.png)
![Screenshot_20201118-233842_Termux](https://user-images.githubusercontent.com/74375581/99630824-1ffd6980-2a00-11eb-8070-f418db204ac4.png)

The development cant continue to count on these elements for a future build, with the exception that a separate build is created for devices like A300FU, the latter if it has hardware support for NFC

**Comment by vlw** [comment]
Nfc related services deleting from a300h when firmware installing using postinstall script. You have to use latest twrp from ashyx

**Comment by Beatz106** [comment]
![Screenshot_2020-11-28-21-46-55](https://user-images.githubusercontent.com/74375581/100532941-67d07d80-31c4-11eb-86ed-856027e204b3.png)


This is the installed version.
