### ISSUE TITLE
Hello, can you see my flashing problem

### ISSUE THREAD

**Issue by xlzhen-940218** [vlw/android_device_samsung_a3lte#7]
The lineage-17.1-20200819-UNOFFICIAL-a3lte.zip downloaded from your account vl_w on the androidfilehost.com website will wait indefinitely after booting up my SM-A3000 mobile phone

**Comment by vlw** [comment]
Use latest TWRT from ashyx (3.3.1)

**Comment by xlzhen-940218** [comment]
![IMG_20201130_095517](https://user-images.githubusercontent.com/16200456/100561048-aa907380-32f2-11eb-81d2-c3a93478621c.jpg)
But I am already the latest version
![image](https://user-images.githubusercontent.com/16200456/100561085-c72cab80-32f2-11eb-9f69-59f7306327a8.png)

**Comment by vlw** [comment]
a3000? send me text https://t.me/vlwwwwww
