### ISSUE TITLE
Is there any chance you will update LineageOS 17.1 for A3lte ? 

### ISSUE THREAD

**Issue by Ud4ba** [vlw/android_device_samsung_a3lte#8]
Any news on SELinux disabled , any chances this gonna change? 
One more think if you can , add bromite webview as default . is this possible? 
thanks for your work mate .

**Comment by vlw** [comment]
17.1 will updated but still without SELinux. 18.1 maybe will get selinux enforced in summer 2021

**Comment by Ud4ba** [comment]
> 
> 
> 17.1 will updated but still without SELinux. 18.1 maybe will get selinux enforced in summer 2021

any news on the update? sorry if i spam you .
